### PR TITLE
Load settings from config.toml file during CDI generation

### LINKED ISSUE #1075: Load settings from config.toml file during CDI generation
Most nvidia-ctk commands do not currently load settings from the config.toml file. The one exception is nvidia-ctk config which processes the same config file that the nvidia-container-runtime would.

(see also https://github.com/NVIDIA/nvidia-container-toolkit/issues/939).

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
This pull request adds logic for `nvidia-ctk cdi generate` to load settings from the config.toml file, the order of importance if (1) command line, (2) environment variable(for those flags with an ENV VAR option), (3) config file.

[no-relnote] extra: migrates to urfave v3

Fixes #1075

### CODE REVIEW

File: cmd/nvidia-ctk/cdi/list/list_test.go [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+		t.Run(tt.name, func(t *testing.T) {
+			// Set up environment variables
+			for k, v := range tt.envVars {
+				old := os.Getenv(k)
+				os.Setenv(k, v)
+				defer os.Setenv(k, old)
+			}
+
+			// Create command
+			cmd := NewCommand(logger.NewMockLogger())
```
Comment (elezar) [inline cmd/nvidia-ctk/cdi/list/list_test.go:70]: See https://github.com/NVIDIA/nvidia-container-toolkit/blob/b934c68bef0b0781b4a4233a6742222d31222af9/internal/lookup/cuda/cuda_test.go#L33

File: internal/modifier/gated.go [hunk 2]
```diff
@@ -37,7 +37,15 @@ import (
 //
 // If not devices are selected, no changes are made.
 func NewFeatureGatedModifier(logger logger.Interface, cfg *config.Config, image image.CUDA, driver *root.Driver, hookCreator discover.HookCreator) (oci.SpecModifier, error) {
-	if devices := image.VisibleDevicesFromEnvVar(); len(devices) == 0 {
+	var devices []string
```
[the remark this answers is not in the document]
Comment (ArangoGutierrez) [reply internal/modifier/gated.go:40]: ah sorry my bad, I was working on the Gated issue, didn't checked the branch and this bit got in here

**Comment by ArangoGutierrez** [comment]
Let's first agree on https://github.com/NVIDIA/nvidia-container-toolkit/pull/1123 , I'll then rebase this PR and continnue the work here

**Comment by ArangoGutierrez** [comment]
PR updated now with a centralized logic at `/internal/config` 
PTAL @elezar

**Comment by ArangoGutierrez** [comment]
With #763 in I would like this PR to go next
cc @elezar

File: internal/config/flags.go [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+// ResolveCDIListConfig resolves the config struct for the CDI list subcommand in-place.
+// It sets cfg.cdiSpecDirs using CLI > config > default priority.
+// Accepts *list.config as the third argument.
+func ResolveCDIListConfig(ctx *cli.Context, config *Config, cfg interface{}) {
+	// Use switch statement for type assertion
+	switch v := cfg.(type) {
+	case *struct{ cdiSpecDirs cli.StringSlice }:
+		var dirs []string
+		switch {
+		case ctx.IsSet("spec-dir"):
```
Comment (elezar) [inline internal/config/flags.go]: In general, I think this is the wrong place to specify this. The flags associated with a config option should not leak to this internal package.

Comment (ArangoGutierrez) [reply internal/config/flags.go]: As discussed, I am now exploring migrating to Urfave v3 and trying to leverage it for this functionality, will update the PR shortly

File: cmd/nvidia-ctk/cdi/generate/generate.go [hunk 4]
```diff
@@ -84,33 +87,37 @@ func (m command) build() *cli.Command {
...
+			return ctx, m.validateFlags(cmd, &opts)
 		},
-		Action: func(c *cli.Context) error {
-			return m.run(c, &opts)
+		Action: func(ctx context.Context, cmd *cli.Command) error {
+			return m.run(cmd, &opts)
 		},
 	}
 
+	configSource := []altsrc.Sourcer{
```
[the remark this answers is not in the document]
Comment (ArangoGutierrez) [reply cmd/nvidia-ctk/cdi/generate/generate.go]: This is no longer needed with V3, `InitInputSourceWithContext` no longer exists on the `altsrc` pkg https://pkg.go.dev/github.com/urfave/cli-altsrc/v3

File: cmd/nvidia-ctk/cdi/generate/generate.go [hunk 5]
```diff
@@ -93,6 +95,10 @@ func (m command) build() *cli.Command {
...
+		altsrc.StringSourcer(config.GetConfigFilePath()),
```
Comment (elezar) [inline cmd/nvidia-ctk/cdi/generate/generate.go]: Note that it's not sufficient to load the config from file since we don't apply the defaults correctly then.

File: cmd/nvidia-cdi-hook/chmod/chmod.go [hunk 6]
```diff
@@ -58,11 +59,11 @@ func (m command) build() *cli.Command {
 	c := cli.Command{
 		Name:  "chmod",
 		Usage: "Set the permissions of folders in the container by running chmod. The container root is prefixed to the specified paths.",
-		Before: func(c *cli.Context) error {
-			return validateFlags(c, &cfg)
+		Before: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
+			return ctx, validateFlags(cmd, &cfg)
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/chmod/chmod.go]: Let's update `validateFlags` and `m.run` to have the signatures:
```
(context.Context, *cli.Command, *config) (context.Context, error)
(context.Context, *cli.Command, *config) error
```
In this way they match the `Before` and `After` functors with the exception that they also accept the options.

File: cmd/nvidia-cdi-hook/cudacompat/cudacompat.go [hunk 7]
```diff
@@ -89,11 +90,11 @@ func (m command) build() *cli.Command {
 	return &c
 }
 
-func (m command) validateFlags(_ *cli.Context, cfg *options) error {
+func (m command) validateFlags(cmd *cli.Command, cfg *options) error {
 	return nil
 }
 
-func (m command) run(_ *cli.Context, cfg *options) error {
+func (m command) run(ctx context.Context, cmd *cli.Command, cfg *options) error {
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/cudacompat/cudacompat.go]: Why are we passing the `ctx` in this case. Let's Replace with:
```
func (m command) run(_ *cli.Command, cfg *options) error {
```
(alternatively update all `Action` targets to accept the context too.

File: cmd/nvidia-cdi-hook/disable-device-node-modification/disable-device-node-modification.go [hunk 8]
```diff
@@ -67,11 +68,11 @@ func NewCommand(logger logger.Interface) *cli.Command {
 	return &c
 }
 
-func validateFlags(c *cli.Context, cfg *options) error {
+func validateFlags(c *cli.Command, cfg *options) error {
 	return nil
 }
 
-func run(_ *cli.Context, cfg *options) error {
+func run(ctx context.Context, cmd *cli.Command, cfg *options) error {
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/disable-device-node-modification/disable-device-node-modification.go]:
```suggestion
func run(_ *cli.Command, cfg *options) error {
```

File: cmd/nvidia-cdi-hook/main.go [hunk 9]
```diff
@@ -44,10 +45,10 @@ func main() {
 	opts := options{}
 
 	// Create the top-level CLI
-	c := cli.NewApp()
+	c := cli.Command{}
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/main.go]: Given that we're now constructing the command directly, let's set the members inline:
```
c := cli.Command{
  Name: "NVIDIA CDI Hook"
  ...
  Action: func(...)
```

File: cmd/nvidia-cdi-hook/main.go [hunk 10]
```diff
@@ -71,19 +72,19 @@ func main() {
...
-			EnvVars: []string{"NVIDIA_CTK_DEBUG", "NVIDIA_CDI_DEBUG"},
+			Sources: cli.EnvVars("NVIDIA_CTK_DEBUG", "NVIDIA_CDI_DEBUG"),
 		},
 		&cli.BoolFlag{
 			Name:        "quiet",
 			Usage:       "Suppress all output except for errors; overrides --debug",
 			Destination: &opts.Quiet,
 			// TODO: Support for NVIDIA_CDI_QUIET is deprecated and NVIDIA_CTK_QUIET should be used instead.
-			EnvVars: []string{"NVDIA_CTK_QUIET", "NVIDIA_CDI_QUIET"},
+			Sources: cli.EnvVars("NVDIA_CTK_QUIET", "NVIDIA_CDI_QUIET"),
```
[the remark this answers is not in the document]
Comment (elezar) [reply cmd/nvidia-cdi-hook/main.go]: Let's make this change.

File: cmd/nvidia-cdi-hook/update-ldcache/update-ldcache.go [hunk 11]
```diff
@@ -97,14 +98,14 @@ func (m command) build() *cli.Command {
...
-func (m command) validateFlags(c *cli.Context, cfg *options) error {
+func (m command) validateFlags(cmd *cli.Command, cfg *options) error {
 	if cfg.ldconfigPath == "" {
 		return errors.New("ldconfig-path must be specified")
 	}
 	return nil
 }
 
-func (m command) run(c *cli.Context, cfg *options) error {
+func (m command) run(ctx context.Context, cmd *cli.Command, cfg *options) error {
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/update-ldcache/update-ldcache.go]: See other `run` comments.

File: cmd/nvidia-ctk-installer/container/container.go [hunk 12]
```diff
@@ -53,15 +53,15 @@ type Options struct {
 }
 
 // ParseArgs parses the command line arguments to the CLI
-func ParseArgs(c *cli.Context, o *Options) error {
+func ParseArgs(c *cli.Command, o *Options) error {
```
Comment (elezar) [inline cmd/nvidia-ctk-installer/container/container.go]: This function is no longer used. Let's remove this in a commit before the migration.

File: cmd/nvidia-ctk-installer/main.go [hunk 13]
```diff
@@ -73,27 +74,27 @@ type app struct {
...
 }
 
-func (a app) build() *cli.App {
+func (a app) build() *cli.Command {
 	options := options{
 		toolkitOptions: toolkit.Options{},
 	}
 	// Create the top-level CLI
-	c := cli.NewApp()
+	c := cli.Command{}
```
Comment (elezar) [inline cmd/nvidia-ctk-installer/main.go]: Initialize the members directly.

File: cmd/nvidia-ctk/main.go [hunk 14]
```diff
@@ -48,11 +49,11 @@ func main() {
 	opts := options{}
 
 	// Create the top-level CLI
-	c := cli.NewApp()
+	c := cli.Command{}
```
Comment (elezar) [inline cmd/nvidia-ctk/main.go]: Set the members directly.

File: cmd/nvidia-cdi-hook/main.go [hunk 15]
```diff
@@ -79,7 +79,7 @@ func main() {
 			Usage:       "Suppress all output except for errors; overrides --debug",
 			Destination: &opts.Quiet,
 			// TODO: Support for NVIDIA_CDI_QUIET is deprecated and NVIDIA_CTK_QUIET should be used instead.
-			Sources: cli.EnvVars("NVDIA_CTK_QUIET", "NVIDIA_CDI_QUIET"),
+			Sources: cli.EnvVars("NVIDIA_CTK_QUIET", "NVIDIA_CDI_QUIET"),
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/main.go]: Let's have this as a separate commit.

File: cmd/nvidia-ctk/cdi/generate/config.go [hunk 16]
```diff
@@ -0,0 +1,139 @@
...
+	defer c.Unlock()
+	if c.source == nil {
+		c.source = altsrc.NewStringPtrSourcer(config)
+	}
+	return c
+}
+
+// LoadIfRequired loads the config file if it has not already been loaded.
+// If the config file path is not specified, it uses the default config file path.
+func (c *configAsValueSource) LoadIfRequired() error {
```
Comment (elezar) [inline cmd/nvidia-ctk/cdi/generate/config.go]: This should probably be private: `loadIfRequired`.

File: cmd/nvidia-ctk/cdi/generate/generate.go [hunk 17]
```diff
@@ -93,7 +100,13 @@ func (m command) build() *cli.Command {
...
 	}
 
-	c.Flags = []cli.Flag{
+	flags = []cli.Flag{
+		&cli.StringFlag{
+			Name:        "config",
+			Usage:       "Specify the path to the config file to use",
+			Destination: &opts.config,
+			Sources:     cli.EnvVars("NVIDIA_CTK_CONFIG_FILE"),
+		},
```
Comment (elezar) [inline cmd/nvidia-ctk/cdi/generate/generate.go]: It almost feels as if we need to set this as part of the `nvidia-ctk` top-level command and then pass it in to the subcommand constructor. Otherwise we're going to have to reimplement this for every subcommand.

File: cmd/nvidia-cdi-hook/chmod/chmod.go (hunk 6 above)
Comment (elezar) [reply cmd/nvidia-cdi-hook/chmod/chmod.go]: Let's rather leave them as is from the context of this change.

File: cmd/nvidia-ctk/cdi/generate/generate.go (hunk 17 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-ctk/cdi/generate/generate.go]: it is now a top-level command flag and passed over subcommand constructor

File: cmd/nvidia-ctk/cdi/generate/config.go (hunk 16 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-ctk/cdi/generate/config.go]: done

File: cmd/nvidia-cdi-hook/main.go (hunk 15 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/main.go]: done

File: cmd/nvidia-ctk/main.go (hunk 14 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-ctk/main.go]: done

File: cmd/nvidia-ctk-installer/container/container.go (hunk 12 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-ctk-installer/container/container.go]: done

File: cmd/nvidia-cdi-hook/main.go (hunk 9 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/main.go]: done

File: cmd/nvidia-cdi-hook/disable-device-node-modification/disable-device-node-modification.go (hunk 8 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/disable-device-node-modification/disable-device-node-modification.go]: done

File: cmd/nvidia-cdi-hook/cudacompat/cudacompat.go (hunk 7 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/cudacompat/cudacompat.go]: done

File: cmd/nvidia-cdi-hook/update-ldcache/update-ldcache.go [hunk 18]
```diff
@@ -65,21 +65,22 @@ func (m command) build() *cli.Command {
...
+		Action: func(ctx context.Context, cmd *cli.Command) error {
+			return m.run(cmd, &cfg)
 		},
 	}
 
 	c.Flags = []cli.Flag{
 		&cli.StringSliceFlag{
-			Name:        "folder",
-			Usage:       "Specify a folder to add to /etc/ld.so.conf before updating the ld cache",
-			Destination: &cfg.folders,
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/update-ldcache/update-ldcache.go:82]: Do you have a reference for this change?

Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/update-ldcache/update-ldcache.go:82]: moving all the c.something into the `c:= cli.Command` initialization

File: cmd/nvidia-cdi-hook/chmod/chmod.go [hunk 19]
```diff
@@ -56,13 +57,15 @@ func (m command) build() *cli.Command {
...
 	// Create the 'chmod' command
 	c := cli.Command{
-		Name:  "chmod",
-		Usage: "Set the permissions of folders in the container by running chmod. The container root is prefixed to the specified paths.",
-		Before: func(c *cli.Context) error {
-			return validateFlags(c, &cfg)
+		Name:                   "chmod",
+		Usage:                  "Set the permissions of folders in the container by running chmod. The container root is prefixed to the specified paths.",
+		UseShortOptionHandling: true,
+		EnableShellCompletion:  true,
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/chmod/chmod.go]: Nit: This functionality is new.

File: cmd/nvidia-cdi-hook/disable-device-node-modification/disable-device-node-modification.go (hunk 8 above)
Comment (elezar) [reply cmd/nvidia-cdi-hook/disable-device-node-modification/disable-device-node-modification.go]: Not critical, but was there a reason for not just replacing cli.Context with cli.Command?

File: cmd/nvidia-ctk-installer/container/container.go [hunk 20]
```diff
@@ -52,27 +51,6 @@ type Options struct {
...
-		return fmt.Errorf("incorrect number of arguments")
-	}
-
-	o.RuntimeDir = args.Get(0)
-
-	logrus.Infof("Successfully parsed arguments")
-
-	return nil
-}
-
```
Comment (elezar) [inline cmd/nvidia-ctk-installer/container/container.go:75]: Nit: could be an extra commit.

File: cmd/nvidia-cdi-hook/chmod/chmod.go [hunk 21]
```diff
@@ -64,26 +64,25 @@ func (m command) build() *cli.Command {
 		Before: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
 			return ctx, m.validateFlags(cmd, &cfg)
 		},
-		Action: func(ctx context.Context, cmd *cli.Command) error {
-			return m.run(cmd, &cfg)
+		Action: func(_ context.Context, _ *cli.Command) error {
+			return m.run(nil, &cfg)
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/chmod/chmod.go]: Please don't pass `nil` into the `run()` function. This also doesn't seem to be related to adding a config file.
