### PR TITLE
Fix handling of unrecognised CDI hooks

### LINKED ISSUE #1225: CLI flags should be ignored when an unrecognised hook is detected
In #1000 we tried to avoid failures for unsupported hooks (to allow some version skew between toolkit versions). This does not work as expected beacaus the flags passed to the unexepected hook cause an error:

```
$ nvidia-cdi-hook create-soname-symlinks --folder foo
Incorrect Usage: flag provided but not defined: -folder

NAME:
   NVIDIA CDI Hook - Command to structure files for usage inside a container, called as hooks from a container runtime, defined in a CDI yaml file

USAGE:
   NVIDIA CDI Hook [global options] [command [command options]]

VERSION:
   1.18.0-rc.2
commit: 08b3a388e7b1d447e10d4c4d4a71dca29a98a964

COMMANDS:
   update-ldcache                    Update ldcache in a container by running ldconfig
   create-symlinks                   A hook to create symlinks in the container.
   chmod                             Set the permissions of folders in the container by running chmod. The container root is prefixed to the specified paths.
   enable-cuda-compat                This hook ensures that the folder containing the CUDA compat libraries is added to the ldconfig search path if required.
   disable-device-node-modification  Ensure that the /proc/driver/nvidia/params file present in the container does not allow device node modifications.
   help, h                           Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug, -d    Enable debug-level logging (default: false) [$NVIDIA_CTK_DEBUG, $NVIDIA_CDI_DEBUG]
   --quiet        Suppress all output except for errors; overrides --debug (default: false) [$NVIDIA_CTK_QUIET, $NVIDIA_CDI_QUIET]
   --help, -h     show help
   --version, -v  print the version
ERRO[0000] flag provided but not defined: -folder
```

Should give:
```
$ nvidia-cdi-hook create-soname-symlinks
WARN[0000] Unsupported CDI hook: create-soname-symlinks
```

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Fixes #1225

Previously, when an unrecognized CDI hook was invoked with command-line flags, the nvidia-cdi-hook command would fail with a flag parsing error instead of gracefully handling the unsupported hook. This could cause container launch failures when CDI specifications reference hooks that are not yet supported by the current NVIDIA Container Toolkit version.

This PR enhances the error handling in nvidia-cdi-hook to gracefully handle unrecognized CDI hooks that include command-line flags. The changes ensure that:
Unrecognized hooks with flags are handled gracefully - Instead of failing with flag parsing errors, the command now issues a warning and continues
Backwards compatibility is maintained - Existing behavior for supported hooks remains unchanged
Container launches don't fail - Unsupported hooks result in warnings rather than errors
Changes
Added OnUsageError handler in ConfigureCDIHookCommand to detect flag parsing errors for unrecognized commands
Added strings import for error message parsing to identify flag-related errors
Enhanced error detection to specifically catch "flag provided but not defined" errors for unrecognized hooks
Improved warning consistency by reusing the existing IssueUnsupportedHookWarning logic

# Test Cases
The following test cases demonstrate the improved behavior:

Before (failing):

```bash
$ ./nvidia-cdi-hook unknown-hook --some-flag value
Error: flag provided but not defined: -some-flag
```

After (graceful handling):

```bash
$ ./nvidia-cdi-hook unknown-hook --some-flag value
time="2025-09-22T11:25:26+02:00" level=warning msg="Unsupported CDI hook: unknown-hook"
```

Additional test cases:

```bash
# Unrecognized hook without flags
$ ./nvidia-cdi-hook unknown-hook
time="2025-09-22T11:25:26+02:00" level=warning msg="Unsupported CDI hook: unknown-hook"

# No hook specified
$ ./nvidia-cdi-hook
time="2025-09-22T11:25:26+02:00" level=warning msg="No CDI hook specified"

# Recognized hook with valid flags (unchanged behavior)
$ ./nvidia-cdi-hook update-ldcache --debug
# Works as expected, no warning

# Recognized hook with invalid flags (unchanged behavior)
$ ./nvidia-cdi-hook update-ldcache --invalid-flag
Error: flag provided but not defined: -invalid-flag
```

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Tested 

```bash
./nvidia-cdi-hook unknown-hook --some-flag value 
time="2025-09-22T11:25:26+02:00" level=warning msg="Unsupported CDI hook: unknown-hook"
```

File: cmd/nvidia-cdi-hook/main.go [hunk 1]
```diff
@@ -72,6 +73,26 @@ func main() {
 			commands.IssueUnsupportedHookWarning(logger, cmd)
 			return nil
 		},
+		// Handle usage errors to catch unrecognized hooks with flags
+		OnUsageError: func(ctx context.Context, cmd *cli.Command, err error, isSubcommand bool) error {
+			// Check if this is a "flag provided but not defined" error
+			errMsg := err.Error()
+			if strings.HasPrefix(errMsg, "flag provided but not defined: ") {
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/main.go]: One nit: The err in `urfave` is defined as:
```
providedButNotDefinedErrMsg = "flag provided but not defined: -"
```
and we don't include the `-` here.

**Review by elezar — DISMISSED** [review]
What about the case of a subcommand that does not accept arguments:
```
$ ./nvidia-cdi-hook foo
No help topic for 'foo'
$ echo $?
3
```

File: cmd/nvidia-cdi-hook/main.go (hunk 1 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/main.go]: ah yeah, let me edit!

Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/main.go]: edited

File: cmd/nvidia-cdi-hook/main.go [hunk 2]
```diff
@@ -72,6 +73,35 @@ func main() {
 			commands.IssueUnsupportedHookWarning(logger, cmd)
 			return nil
 		},
+		// Handle usage errors to catch unrecognized hooks
+		OnUsageError: func(ctx context.Context, cmd *cli.Command, err error, isSubcommand bool) error {
+			errMsg := err.Error()
+
+			// Check if this is a "No help topic for" error (unrecognized
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/main.go]: Since in Urfave we have a [`CommandNotFound` handler](https://github.com/urfave/cli/blob/de9b5b4e61b0cce132f2a2bc73261eb0601d76ce/help.go#L318-L329) does it not make sense to handle this separately?

File: cmd/nvidia-ctk/hook/hook.go [hunk 3]
```diff
@@ -54,6 +55,29 @@ func (m hookCommand) build() *cli.Command {
 			commands.IssueUnsupportedHookWarning(m.logger, cmd)
 			return nil
 		},
+		// Handle unrecognized commands when help is requested (e.g., help
+		// unknowncommand)
+		CommandNotFound: func(ctx context.Context, cmd *cli.Command, commandName string) {
```
Comment (elezar) [inline cmd/nvidia-ctk/hook/hook.go]: These and the `Action` are now strictly duplicated from `nvidia-cdi-hook`. I don't think this is required with `urfave/v3`. Do we want to refactor this?

Comment (ArangoGutierrez) [reply cmd/nvidia-ctk/hook/hook.go]: I did a small refactor, creating a shared function so we don't have duplicated code

File: cmd/nvidia-cdi-hook/commands/commands.go [hunk 4]
```diff
@@ -51,3 +54,45 @@ func IssueUnsupportedHookWarning(logger logger.Interface, c *cli.Command) {
 		logger.Warningf("Unsupported CDI hook: %v", args[0])
 	}
 }
+
+// NewHookCommand creates a new hook command with common behavior for handling
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/commands/commands.go]: Nit: This is specifically CDI hooks, so maybe rename `NewCDIHookCommand`?

File: cmd/nvidia-cdi-hook/commands/commands.go [hunk 5]
```diff
@@ -51,3 +54,45 @@ func IssueUnsupportedHookWarning(logger logger.Interface, c *cli.Command) {
...
+		// older NVIDIA Container Toolkit version or a hook that has been removed
+		// in newer version.
+		Action: func(ctx context.Context, cmd *cli.Command) error {
+			IssueUnsupportedHookWarning(logger, cmd)
+			return nil
+		},
+		// Handle unrecognized commands when help is requested (e.g., help
+		// unknowncommand)
+		CommandNotFound: func(ctx context.Context, cmd *cli.Command, commandName string) {
+			logger.Warningf("Unsupported CDI hook: %v", commandName)
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/commands/commands.go]: Question: Is there a reason that we don't call `IssueUnsupportedHookWarning` (or at least reuse some of the logic there)?

File: cmd/nvidia-cdi-hook/commands/commands.go [hunk 6]
```diff
@@ -51,3 +54,45 @@ func IssueUnsupportedHookWarning(logger logger.Interface, c *cli.Command) {
...
+			// If this is a flag parsing error for an unrecognized command,
+			// suppress it and let the default Action handle it
+			errMsg := err.Error()
+			if strings.HasPrefix(errMsg, "flag provided but not defined: -") {
+				// Check if the first argument is an unrecognized command
+				args := cmd.Args().Slice()
+				if len(args) > 0 && cmd.Command(args[0]) == nil {
+					// This is an unrecognized hook with flags - the default
+					// Action will handle it
+					return nil
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/commands/commands.go]: Should we not issue a warning here?

File: cmd/nvidia-cdi-hook/main.go [hunk 7]
```diff
@@ -44,52 +44,37 @@ func main() {
 	// Create a options struct to hold the parsed environment variables or command line flags
 	opts := options{}
 
-	// Create the top-level CLI
-	c := cli.Command{
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/main.go:48]: Does it make sense to still construct the `Command`s and then call a fuction to modify the members that we want instead?

File: cmd/nvidia-cdi-hook/commands/commands.go [hunk 8]
```diff
@@ -51,3 +54,47 @@ func IssueUnsupportedHookWarning(logger logger.Interface, c *cli.Command) {
 		logger.Warningf("Unsupported CDI hook: %v", args[0])
 	}
 }
+
+// ConfigureCDIHookCommand takes a base command and adds the common CDI hook
+// behavior for handling unsupported hooks.
+// The base command should have Name, Usage, and Version set as desired.
+func ConfigureCDIHookCommand(base *cli.Command, logger logger.Interface) *cli.Command {
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/commands/commands.go]: The comment seems to indicate that we should call the functions something like `AddUnsupportedHooksChecks` but we do add the subcommands at the end, so it's probably just the comment that needs to be udpated for accuracy.

File: cmd/nvidia-cdi-hook/main.go [hunk 9]
```diff
@@ -44,54 +44,41 @@ func main() {
...
-		// to launch. An unsupported hook could be the result of a CDI specification
-		// referring to a new hook that is not yet supported by an older NVIDIA
-		// Container Toolkit version or a hook that has been removed in newer
-		// version.
-		Action: func(ctx context.Context, cmd *cli.Command) error {
-			commands.IssueUnsupportedHookWarning(logger, cmd)
-			return nil
+	}
+	// Set log-level for all subcommands
+	c.Before = func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/main.go]: Givent that we're only ADDing to the hook in the new function, I would not expect this to be part of the diff.

**Comment by elezar** [comment]
Let's update the description to show the output for the various test cases.

File: cmd/nvidia-cdi-hook/commands/commands.go [hunk 10]
```diff
@@ -51,3 +54,46 @@ func IssueUnsupportedHookWarning(logger logger.Interface, c *cli.Command) {
 		logger.Warningf("Unsupported CDI hook: %v", args[0])
 	}
 }
+
+// ConfigureCDIHookCommand takes a base command and configures it to handle
+// unsupported CDI hooks gracefully.
```
Comment (elezar) [inline cmd/nvidia-cdi-hook/commands/commands.go]: This is still not accurate.

Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/commands/commands.go]: How about now?

File: cmd/nvidia-cdi-hook/main.go (hunk 9 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/main.go]: The diff has been updated

File: cmd/nvidia-cdi-hook/commands/commands.go (hunk 8 above)
Comment (ArangoGutierrez) [reply cmd/nvidia-cdi-hook/commands/commands.go]: Func doc comment has been updated

**Review by elezar — APPROVED** [review]
